sudo: false

language: rust
os: linux
rust:
  - stable
  - nightly

matrix:
  include:
  - os: windows
    rust: stable
  - os: osx
    rust: stable
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"

# Inspired by https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry


install:
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then rustup component add rustfmt; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then rustup component add clippy; fi

script:
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then cargo fmt --all -- --check; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then cargo clippy --all --all-targets -- -D clippy::all; fi
  - cargo test --all -- --nocapture
